server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - application/javascript
      - text/html
      - text/xml
      - text/plain
      - text/css
    min-response-size: 2048
  tomcat:
    max-threads: 1000
    max-connections: 10000


spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    redisson:
      file: classpath:redission/redisson-local.yml
  shardingsphere:
    datasource:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 100
        maxActive: 100
        maxWait: 3000
        minEvictableIdleTimeMillis: 7200000
        minIdle: 100
        password: devMysqlPasswd
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 7200000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.1.101:3306/${parentArtifactId}?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
        username: root
      names: master
    props:
      sql:
        show: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.101:8848
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: tech.muyi.core.dao

dubbo:
  scan:
    basePackages: tech.muyi
  protocol:
    name: dubbo
    port: -1
    threads: 100
  registry:
    address: spring-cloud://192.168.1.101:8848
  cloud:
    subscribed-services: '*'
    retries: 0
    check: false

nacos:
  config:
    server-addr: 192.168.1.101:8848
    namespace: e21577a8-c9f9-4320-bf4d-9c4b7fa83494
